### ISSUE TITLE
Avoid side effects

### ISSUE THREAD

**Issue by leocavalcante** [erandirjunior/easy-route#2]
Avoid side effects on files that declare symbols:
- https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#23-side-effects

Just let the exception to be thrown and delegate to the lib user the ability to handle it the way she/he wants.

https://github.com/fsoaresjunior/easy-route/blob/e8500e08ff708176a3ca5d3442ae151936a7587d/src/Bootstrap.php#L83

**Comment by eduardogalbiati** [comment]
Besides removing the try/catch block you should implement your own exceptions, for example when a controller or a method is not found

**Comment by leocavalcante** [comment]
Closed due inactivity.
